{
 "title": "Detector Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "detector",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n  bucket: \"Data\",\n  tag: \"sensor_id\",\n  predicate: (r) => r._measurement == \"mqtt_consumer\" and r.topic == \"radiation/detectors\",\n  start: -30d\n)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dose Rate Time Series",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "uSv/h" } },
   "targets": [
    {
     "query": "from(bucket: \"Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r._field == \"gamma_current_dose_uSv_h\" or r._field == \"neutron_current_dose_uSv_h\")\n  |> filter(fn: (r) => r.host == \"VISR\")\n  |> filter(fn: (r) => r.sensor_id =~ /^${detector:regex}$/)\n  |> filter(fn: (r) => r.topic == \"radiation/detectors\")\n  |> map(fn: (r) => ({\n      r with\n      _field: if r._field == \"gamma_current_dose_uSv_h\" then \"Gamma dose (µSv/h)\"\n              else \"Neutron dose (µSv/h)\"\n    }))"
    }
   ]
  },
  {
   "title": "Gamma Count Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r._field == \"gamma_current_count_rate_cps\")\n  |> filter(fn: (r) => r.host == \"VISR\")\n  |> filter(fn: (r) => r.sensor_id =~ /^${detector:regex}$/)\n  |> filter(fn: (r) => r.topic == \"radiation/detectors\")"
    }
   ]
  },
  {
   "title": "Neutron Count Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r._field == \"neutron_current_count_rate_cps\")\n  |> filter(fn: (r) => r.host == \"VISR\")\n  |> filter(fn: (r) => r.sensor_id =~ /^${detector:regex}$/)\n  |> filter(fn: (r) => r.topic == \"radiation/detectors\")"
    }
   ]
  }
 ]
}