apiVersion: 1

datasources:
  - name: Geo CSV
    type: yesoreyeram-infinity-datasource
    access: proxy
    editable: true
    jsonData:
      allowedHosts:
        - http://datasets/
	- http://192.168.1.188:11434/